/*globals define*/

define([
	"./loadMain",
	"./loadFrontPage",
	"./loadFooterSection",
	"./loadHeaderSection",
	"./loadAppointmentPage",
	"./loadAppointmentEntry",
	"./loadAppointmentList",
	"./loadContactPage",
	"./loadContactEntry",
	"./loadContactList",
	"./loadNotePage",
	"./loadNoteEntry",
	"./loadNoteList",
	"./loadTaskPage",
	"./loadTaskEntry",
	"./loadTaskList",
	"./loadMenu",
	"./loadInfoDialog",
	"./showConnectivityMessage",
	"./downloadServerData",
	"./getallfromlocalstorage",
	"./doSave",
	"./doDelete",
	"./pageShowHandler",
	"./populateList",
	"./viewEditItem",
	"./clearData",
	"./loadFrame",
	"./loadAboutPanel",
	"./loadConfirmDialog"
], function (
	loadMain,
	loadFrontPage,
	loadFooterSection,
	loadHeaderSection,
	loadAppointmentPage,
	loadAppointmentEntry,
	loadAppointmentList,
	loadContactPage,
	loadContactEntry,
	loadContactList,
	loadNotePage,
	loadNoteEntry,
	loadNoteList,
	loadTaskPage,
	loadTaskEntry,
	loadTaskList,
	loadMenu,
	loadInfoDialog,
	showConnectivityMessage,
	downloadServerData,
	getAllFromLocalStorage,
	doSave,
	doDelete,
	pageShowHandler,
	populateList,
	viewEditItem,
	clearData,
	loadFrame,
	loadAboutPanel,
	loadConfirmDialog
) {

	return {
		loadMain: loadMain,
		loadFrontPage: loadFrontPage,
		loadFooterSection: loadFooterSection,
		loadHeaderSection: loadHeaderSection,
		loadAppointmentPage: loadAppointmentPage,
		loadAppointmentEntry: loadAppointmentEntry,
		loadAppointmentList: loadAppointmentList,
		loadContactPage: loadContactPage,
		loadContactEntry: loadContactEntry,
		loadContactList: loadContactList,
		loadNotePage: loadNotePage,
		loadNoteEntry: loadNoteEntry,
		loadNoteList: loadNoteList,
		loadTaskPage: loadTaskPage,
		loadTaskEntry: loadTaskEntry,
		loadTaskList: loadTaskList,
		loadMenu: loadMenu,
		loadInfoDialog: loadInfoDialog,
		showConnectivityMessage: showConnectivityMessage,
		downloadServerData: downloadServerData,
		getAllFromLocalStorage: getAllFromLocalStorage,
		doSave: doSave,
		doDelete: doDelete,
		pageShowHandler: pageShowHandler,
		populateList: populateList,
		viewEditItem: viewEditItem,
		clearData: clearData,
		loadFrame: loadFrame,
		loadAboutPanel: loadAboutPanel,
		loadConfirmDialog: loadConfirmDialog
	};

});